name: EssentialsRemake
main: me.cashvillan.essentialsremake.Main
version: 1.0

commands:
  seen:
    usage: /<command>
    description: Check a player.
  fly:
    usage: /<command>
    description: Toggle flight.
  gm:
    usage: /<command>
    description: Toggle gamemodes.